adrec-tp-symfony/src/Entity/Artiste.php
<?php

namespace App\Entity;

use App\Repository\ArtisteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArtisteRepository::class)
 */
class Artiste
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nationality;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $beginning_year;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(?string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }




    public function getBeginningYear(): ?int
    {
        return $this->beginning_year;
    }

    public function setBeginningYear(?int $beginning_year): self
    {
        $this->beginning_year = $beginning_year;

        return $this;
    }
}

adrec-tp-symfony/src/Entity/Song.php
<?php

namespace App\Entity;

use App\Repository\SongRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SongRepository::class)
 */
class Song
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=6)
     */
    private $duration;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDuration(): ?string
    {
        return $this->duration;
    }

    public function setDuration(string $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }
}

adrec-tp-symfony/src/Form/ArtisteType.php
<?php

namespace App\Form;

use App\Entity\Artiste;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArtisteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('nationality')
            ->add('beginning_year')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Artiste::class,
        ]);
    }
}

adrec-tp-symfony/src/Controller/ArtisteController.php
<?php

namespace App\Controller;

use App\Entity\Artiste;
use App\Form\ArtisteType;
use App\Repository\ArtisteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/artiste")
 */
class ArtisteController extends AbstractController
{
    /**
     * @Route("/", name="artiste_index", methods={"GET"})
     */
    public function index(ArtisteRepository $artisteRepository): Response
    {
        return $this->render('artiste/index.html.twig', [
            'artistes' => $artisteRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="artiste_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $artiste = new Artiste();
        $form = $this->createForm(ArtisteType::class, $artiste);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($artiste);
            $entityManager->flush();

            return $this->redirectToRoute('artiste_index');
        }

        return $this->render('artiste/new.html.twig', [
            'artiste' => $artiste,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="artiste_show", methods={"GET"})
     */
    public function show(Artiste $artiste): Response
    {
        return $this->render('artiste/show.html.twig', [
            'artiste' => $artiste,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="artiste_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Artiste $artiste): Response
    {
        $form = $this->createForm(ArtisteType::class, $artiste);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('artiste_index');
        }

        return $this->render('artiste/edit.html.twig', [
            'artiste' => $artiste,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="artiste_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Artiste $artiste): Response
    {
        if ($this->isCsrfTokenValid('delete'.$artiste->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($artiste);
            $entityManager->flush();
        }

        return $this->redirectToRoute('artiste_index');
    }
}

adrec-tp-symfony/templates/album/_delete_form.html.twig
<form method="post" action="{{ path('album_delete', {'id': album.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ album.id) }}">
    <button class="btn">Delete</button>
</form>

adrec-tp-symfony/templates/album/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

adrec-tp-symfony/templates/album/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Album{% endblock %}

{% block body %}
    <h1>Edit Album</h1>

    {{ include('album/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('album_index') }}">back to list</a>

    {{ include('album/_delete_form.html.twig') }}
{% endblock %}

adrec-tp-symfony/templates/album/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album index{% endblock %}

{% block body %}
    <h1>Album index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Published_year</th>
                <th>Price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for album in albums %}
            <tr>
                <td>{{ album.id }}</td>
                <td>{{ album.name }}</td>
                <td>{{ album.publishedYear }}</td>
                <td>{{ album.price }}</td>
                <td>
                    <a href="{{ path('album_show', {'id': album.id}) }}">show</a>
                    <a href="{{ path('album_edit', {'id': album.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('album_new') }}">Create new</a>
{% endblock %}

adrec-tp-symfony/templates/album/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Album{% endblock %}

{% block body %}
    <h1>Create new Album</h1>

    {{ include('album/_form.html.twig') }}

    <a href="{{ path('album_index') }}">back to list</a>
{% endblock %}

adrec-tp-symfony/templates/album/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album{% endblock %}

{% block body %}
    <h1>Album</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ album.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ album.name }}</td>
            </tr>
            <tr>
                <th>Published_year</th>
                <td>{{ album.publishedYear }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ album.price }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('album_index') }}">back to list</a>

    <a href="{{ path('album_edit', {'id': album.id}) }}">edit</a>

    {{ include('album/_delete_form.html.twig') }}
{% endblock %}

adrec-tp-symfony/templates/artiste/_delete_form.html.twig
<form method="post" action="{{ path('artiste_delete', {'id': artiste.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artiste.id) }}">
    <button class="btn">Delete</button>
</form>

adrec-tp-symfony/templates/artiste/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

adrec-tp-symfony/templates/artiste/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Artiste{% endblock %}

{% block body %}
    <h1>Edit Artiste</h1>

    {{ include('artiste/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('artiste_index') }}">back to list</a>

    {{ include('artiste/_delete_form.html.twig') }}
{% endblock %}

adrec-tp-symfony/templates/artiste/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artiste index{% endblock %}

{% block body %}
    <h1>Artiste index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Nationality</th>
                <th>Beginning_year</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for artiste in artistes %}
            <tr>
                <td>{{ artiste.id }}</td>
                <td>{{ artiste.name }}</td>
                <td>{{ artiste.nationality }}</td>
                <td>{{ artiste.beginningYear }}</td>
                <td>
                    <a href="{{ path('artiste_show', {'id': artiste.id}) }}">show</a>
                    <a href="{{ path('artiste_edit', {'id': artiste.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('artiste_new') }}">Create new</a>
{% endblock %}

adrec-tp-symfony/templates/artiste/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Artiste{% endblock %}

{% block body %}
    <h1>Create new Artiste</h1>

    {{ include('artiste/_form.html.twig') }}

    <a href="{{ path('artiste_index') }}">back to list</a>
{% endblock %}

adrec-tp-symfony/templates/artiste/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artiste{% endblock %}

{% block body %}
    <h1>Artiste</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ artiste.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ artiste.name }}</td>
            </tr>
            <tr>
                <th>Nationality</th>
                <td>{{ artiste.nationality }}</td>
            </tr>
            <tr>
                <th>Beginning_year</th>
                <td>{{ artiste.beginningYear }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('artiste_index') }}">back to list</a>

    <a href="{{ path('artiste_edit', {'id': artiste.id}) }}">edit</a>

    {{ include('artiste/_delete_form.html.twig') }}
{% endblock %}

adrec-tp-symfony/templates/footer.html.twig
{% extends 'base.html.twig' %}
<hr>
<div class="footer">
    <p>ici se trouve le footer</p>
</div>

adrec-tp-symfony/templates/genre/_delete_form.html.twig
<form method="post" action="{{ path('genre_delete', {'id': genre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ genre.id) }}">
    <button class="btn">Delete</button>
</form>

adrec-tp-symfony/templates/genre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

adrec-tp-symfony/templates/genre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Genre{% endblock %}

{% block body %}
    <h1>Edit Genre</h1>

    {{ include('genre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('genre_index') }}">back to list</a>

    {{ include('genre/_delete_form.html.twig') }}
{% endblock %}

adrec-tp-symfony/templates/genre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Genre index{% endblock %}

{% block body %}
    <h1>Genre index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for genre in genres %}
            <tr>
                <td>{{ genre.id }}</td>
                <td>{{ genre.name }}</td>
                <td>
                    <a href="{{ path('genre_show', {'id': genre.id}) }}">show</a>
                    <a href="{{ path('genre_edit', {'id': genre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('genre_new') }}">Create new</a>
{% endblock %}

adrec-tp-symfony/templates/genre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Genre{% endblock %}

{% block body %}
    <h1>Create new Genre</h1>

    {{ include('genre/_form.html.twig') }}

    <a href="{{ path('genre_index') }}">back to list</a>
{% endblock %}

adrec-tp-symfony/templates/genre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Genre{% endblock %}

{% block body %}
    <h1>Genre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ genre.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ genre.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('genre_index') }}">back to list</a>

    <a href="{{ path('genre_edit', {'id': genre.id}) }}">edit</a>

    {{ include('genre/_delete_form.html.twig') }}
{% endblock %}

adrec-tp-symfony/templates/header.html.twig
{% extends 'base.html.twig' %}
<hr>
<div class="header">
    <p>ici se trouve le header</p>
</div>